---
- name: leapp_unsupported_network_configuration | Rename kernel named interfaces to predictable names
  vars:
    src_prefix: "eth"
    dst_prefix: "em"
    osnet_conf: "/etc/os-net-config/config.json"
    src_interfaces: "{{ ansible_interfaces | select('match', src_prefix ~ '.*') | sort | list }}"
    undercloud_conf: "~/undercloud.conf"
  block:
    - name: leapp_unsupported_network_configuration | Debug interfaces to rename
      ansible.builtin.debug:
        msg: "{{ src_interfaces }}"

    - name: leapp_unsupported_network_configuration | Update udev rules
      ansible.builtin.lineinfile:
        line: >
          SUBSYSTEM=="net",
          ACTION=="add",
          DRIVERS=="?*",
          ATTR{address}=="{{ ansible_facts[item]['perm_macaddress'] | default(ansible_facts[item]['macaddress']) }}",
          NAME="{{ item | replace(src_prefix, dst_prefix) }}"
        path: /etc/udev/rules.d/70-rhosp-persistent-net.rules
        create: true
      loop: "{{ src_interfaces | reject('match', '^.*\\..*$') | list }}"

    - name: leapp_unsupported_network_configuration | Check that src_prefix files exists
      ansible.builtin.stat:
        path: /etc/sysconfig/network-scripts/ifcfg-{{ item }}
      register: nic_result
      loop: "{{ src_interfaces }}"

    - name: leapp_unsupported_network_configuration | Copy ifcfg files using dst_prefix
      ansible.builtin.copy:
        remote_src: true
        src: "{{ item.stat.path }}"
        dest: "{{ item.stat.path | replace(src_prefix, dst_prefix) }}"
      loop: "{{ nic_result.results }}"
      when: item.stat.exists
      loop_control:
        label: "{{ item.item }}"

    - name: leapp_unsupported_network_configuration | Edit NAME in new network-script files
      ansible.builtin.lineinfile:
        regexp: "^NAME=.*"
        line: "NAME={{ item.item | replace(src_prefix, dst_prefix) }}"
        path: "{{ item.stat.path | replace(src_prefix, dst_prefix) }}"
      loop: "{{ nic_result.results }}"
      when: item.stat.exists
      loop_control:
        label: "{{ item.item }}"

    - name: leapp_unsupported_network_configuration | Edit DEVICE in new network-script files
      ansible.builtin.lineinfile:
        regexp: "^DEVICE=.*"
        line: "DEVICE={{ item.item | replace(src_prefix, dst_prefix) }}"
        path: "{{ item.stat.path | replace(src_prefix, dst_prefix) }}"
      loop: "{{ nic_result.results }}"
      when: item.stat.exists
      loop_control:
        label: "{{ item.item }}"

    - name: leapp_unsupported_network_configuration | Backup old ifcfg network-script files
      ansible.builtin.copy:
        remote_src: true
        src: "{{ item.stat.path }}"
        dest: "{{ item.stat.path }}.bak"
      loop: "{{ nic_result.results }}"
      when: item.stat.exists
      loop_control:
        label: "{{ item.item }}"

    - name: leapp_unsupported_network_configuration | Remove old ifcfg network-script files
      ansible.builtin.file:
        path: "{{ item.stat.path }}"
        state: absent
      loop: "{{ nic_result.results }}"
      when: item.stat.exists
      loop_control:
        label: "{{ item.item }}"

    - name: leapp_unsupported_network_configuration | Check that route files exists
      ansible.builtin.stat:
        path: /etc/sysconfig/network-scripts/route-{{ item }}
      register: route_result
      loop: "{{ src_interfaces }}"

    - name: leapp_unsupported_network_configuration | Copy route files using dst_prefix
      ansible.builtin.copy:
        remote_src: true
        src: "{{ item.stat.path }}"
        dest: "{{ item.stat.path | replace(src_prefix, dst_prefix) }}"
      loop: "{{ route_result.results }}"
      when: item.stat.exists
      loop_control:
        label: "{{ item.item }}"

    - name: leapp_unsupported_network_configuration | Update dst_prefix in route files that use IP command arguments format
      ansible.builtin.replace:
        regexp: "{{ src_prefix }}"
        replace: "{{ dst_prefix }}"
        path: "{{ item.stat.path | replace(src_prefix, dst_prefix) }}"
      loop: "{{ route_result.results }}"
      when: item.stat.exists
      loop_control:
        label: "{{ item.item }}"

    - name: leapp_unsupported_network_configuration | Backup old route files
      ansible.builtin.copy:
        remote_src: true
        src: "{{ item.stat.path }}"
        dest: "{{ item.stat.path }}.bak"
      loop: "{{ route_result.results }}"
      when: item.stat.exists
      loop_control:
        label: "{{ item.item }}"

    - name: leapp_unsupported_network_configuration | Remove old route files
      ansible.builtin.file:
        path: "{{ item.stat.path }}"
        state: absent
      loop: "{{ route_result.results }}"
      when: item.stat.exists
      loop_control:
        label: "{{ item.item }}"

    - name: leapp_unsupported_network_configuration | Get a list of all ifcfg files
      ansible.builtin.find:
        paths: /etc/sysconfig/network-scripts/
        patterns: 'ifcfg-*'
        excludes: '*.bak'
      register: ifcfg_files

    - name: leapp_unsupported_network_configuration | Perform final regex on ifcfg files
      ansible.builtin.replace:
        path: "{{ item[0].path }}"
        regexp: "{{ item[1] }}"
        replace: "{{ item[1] | replace(src_prefix, dst_prefix) }}"
      with_nested:
        - "{{ ifcfg_files.files }}"
        - "{{ src_interfaces }}"
      loop_control:
        label: "{{ item[1] }} -> {{ item[0].path }}"

    - name: leapp_unsupported_network_configuration | Check if undercloud.conf exists
      ansible.builtin.stat:
        path: "{{ undercloud_conf }}"
      register: undercloud_conf_stat

    - name: leapp_unsupported_network_configuration | Replace interface name in undercloud.conf
      ansible.builtin.replace:
        path: "{{ undercloud_conf }}"
        regexp: "{{ item }}"
        replace: "{{ item | replace(src_prefix, dst_prefix) }}"
      when: undercloud_conf_stat.stat.exists
      loop: "{{ src_interfaces }}"

    - name: leapp_unsupported_network_configuration | Check if os-net-config's config.json exists
      ansible.builtin.stat:
        path: "{{ osnet_conf }}"
      register: osnet_conf_stat

    - name: leapp_unsupported_network_configuration | Replace interface name in config.json
      ansible.builtin.replace:
        path: "{{ osnet_conf }}"
        regexp: "{{ item }}"
        replace: "{{ item | replace(src_prefix, dst_prefix) }}"
      when: osnet_conf_stat.stat.exists
      loop: "{{ src_interfaces }}"

    - name: leapp_unsupported_network_configuration | Reboot system to apply network interface changes
      ansible.builtin.reboot:
        reboot_timeout: "{{ reboot_timeout }}"
        post_reboot_delay: "{{ post_reboot_delay }}"
      timeout: "{{ reboot_timeout }}"
      when: src_interfaces | length > 0
...
